#!/usr/bin/env python
#coding=utf-8

import sys
import CosFS
from cosfs_conf import *

if __name__ == '__main__':
    fs = CosFS.CosFS(bucket_id, bucket_key, bucket_secret, bucket_name)

    def ls(args):
        path = '/'
        detail=False
        recursive=False
        
        if len(args) == 0:
            print >>sys.stderr, "command usage: ls <path> [-r|-l|-rl]"
            sys.exit(2)

        path = args[0]
        if len(args) > 1:
            if args[1] in ['-rl', '-lr']:
                detail = True
                recursive = True
            elif args[1] == '-r':
                recursive = True
            elif args[1] == '-l':
                detail = True
            else:
                print >>sys.stderr, "invalid arg %s" % (args[1])
                sys.exit(2)

        fs.ls(path, detail=detail, recursive=recursive)

    def cp(args):
        if len(args) < 2:
            print >>sys.stderr, "command usage: cp <src> <dest> [-f]"
            print >>sys.stderr, "  src/dest may start with `cos:` to indicate it's a cos path"
            sys.exit(2)

        overwrite = len(args) >= 3 and args[2] == '-f'
        fs.cp(args[0], args[1], overwrite)

    def mv(args):
        if len(args) < 2:
            print >>sys.stderr, "command usage: mv <src> <dest>"
            sys.exit(2)

        fs.mv(args[0], args[1])

    def rm(args):
        if len(args) < 1:
            print >>sys.stderr, "command usage: rm <path>"
            sys.exit(2)

        fs.rm(args[0])

    def mkdir(args):
        if len(args) < 1:
            print >>sys.stderr, "command usage: mkdir <path>"
            sys.exit(2)

        fs.mkdir(args[0])

    def rmdir(args):
        if len(args) < 1:
            print >>sys.stderr, "command usage: rmdir <path> [-r]"
            sys.exit(2)

        recursive = len(args) > 1 and args[1] == '-r'
        fs.rmdir(args[0], recursive)

    def cpdir(args):
        if len(args) < 2:
            print >>sys.stderr, "command usage: cpdir <src> <dest> [-i]"
            print >>sys.stderr, "  src/dest may start with `cos:` to indicate it's a cos path"
            print >>sys.stderr, "  -i means skip file exists on cos"
            sys.exit(2)

        ignoreFileExists = len(args) > 2 and args[2] == '-i'
        fs.cpdir(args[0], args[1], ignoreFileExists)

    def cat(args):
        if len(args) < 1:
            print >>sys.stderr, "command usage: cat <path>"
            sys.exit(2)

        fs.cat(args[0])

    def stat(args):
        if len(args) < 1:
            print >>sys.stderr, "command usage: stat <path>"
            sys.exit(2)

        fs.stat(args[0])

    exec_conf = {
        'ls': ls,
        'cp': cp,
        'mv': mv,
        'rm': rm,
        'mkdir': mkdir,
        'rmdir': rmdir,
        'cat': cat,
        'stat': stat,
        'cpdir': cpdir,
    }

    if len(sys.argv) < 2 or sys.argv[1] not in exec_conf:
        print 'Usage: %s <command> [arg1, arg2, ...]\ncommand list:' % (sys.argv[0])
        for command in exec_conf.keys():
            print "    %s" % command
        sys.exit(1)

    args = [] if len(sys.argv) <= 2 else sys.argv[2:]

    exec_conf[sys.argv[1]](args)
